### ISSUE TITLE
Facebook: Error updating Objective-C type information. Multiple types 

### ISSUE THREAD

**Issue by sleimanzublidi** [mono/monotouch-bindings#184]
After adding the library "MonoTouch.FacebookConnect.dll" to a project, when I try to open any .xib file on xcode I get the error:

Error updating Objective-C type information. Multiple types (MonoTouch.FacebookConnect.FBGraphObjectProtocol and MonoTouch.FacebookConnect.FBGraphObject) registered with the same Objective-C name: FBGraphObject

**Comment by kcrawded77** [comment]
No, it is not fixed.
