### ISSUE TITLE
How do I add new bindings to this project?

### ISSUE THREAD

**Issue by alexsorokoletov** [mono/monotouch-bindings#242]
Haven't found this in readme/wiki.
I have to offer this project [MTStatusBarOverlay Bindings](https://github.com/alexsorokoletov/MTStatusBarOverlay-Bindings) 

Thank you.

**Comment by jstedfast** [comment]
What you can do is fork monotouch-bindings and then send a pull request.

**Comment by alexsorokoletov** [comment]
Makes sense, thank you.
